"""The published package names no private documents, paths or tooling, and no retired feature names.

Every tracked or new (untracked, not ignored) text file is scanned: code, docs, tests, examples and
notebooks, whose stored outputs are scanned too (embedded images are skipped). A technical claim
cites its measured number or explains itself; it does not point at a document a user cannot open.
"""
from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]

TEXT_SUFFIXES = {".py", ".md", ".ipynb", ".cff", ".toml", ".txt", ".sh", ".yml", ".yaml", ".cfg",
                 ".in", ".json", ".rst", ".ini", ".html", ".gitignore"}

#: Case-insensitive terms.
TERMS = re.compile(
    r"co-authored|generated by|subagent"
    r"|polish"
    r"|mvp_test|mvp_realworld|speed_study|whisper_fix|whisper_dev_sbi|phe_sbi"
    r"|/anchors\b|/home/astrodados|/work/whisper"
    r"|bug_solver|\bharness\b|\bBUG \d\.\d|\bgates? G-[A-C]\b|\bdecision P\d",
    re.IGNORECASE)
#: Case-sensitive terms: "AI" as a word (not "ai" inside an identifier or a band name).
TERMS_CS = re.compile(r"\bAI\b")

#: This file spells the patterns out; the legacy-name check lists an old container name.
EXEMPT = {"tests/test_release_hygiene.py", "tests/test_no_legacy_names.py"}


def _package_files():
    try:
        out = subprocess.run(["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
                             cwd=ROOT, capture_output=True, check=True)
    except (OSError, subprocess.CalledProcessError):
        pytest.skip("not a git checkout")
    paths = sorted({p for p in out.stdout.decode().split("\0") if p})
    return [ROOT / p for p in paths
            if (ROOT / p).is_file() and (Path(p).suffix in TEXT_SUFFIXES or Path(p).name in TEXT_SUFFIXES)]


def _lines(path):
    text = path.read_text(encoding="utf-8")
    if path.suffix != ".ipynb":
        yield from enumerate(text.splitlines(), 1)
        return
    nb = json.loads(text)
    for i, cell in enumerate(nb.get("cells", [])):
        chunks = ["".join(cell.get("source", []))]
        for out in cell.get("outputs", []):
            chunks.append("".join(out.get("text", [])))
            for mime, data in out.get("data", {}).items():
                if mime.startswith("text/"):
                    chunks.append("".join(data) if isinstance(data, list) else str(data))
            chunks.extend(out.get("traceback", []))
        for line in "\n".join(chunks).splitlines():
            yield f"cell {i}", line


def test_no_private_references_or_retired_names():
    offences = []
    for path in _package_files():
        rel = path.relative_to(ROOT).as_posix()
        if rel in EXEMPT:
            continue
        try:
            lines = list(_lines(path))
        except (UnicodeDecodeError, json.JSONDecodeError):
            continue
        for where, line in lines:
            if TERMS.search(line) or TERMS_CS.search(line):
                offences.append(f"{rel}:{where}: {line.strip()[:160]}")
    assert not offences, f"{len(offences)} line(s) to clean:\n" + "\n".join(offences)
